In [7]:
import pandas as pd
import numpy as np
data = {
    'A': [1, 1, 3, 3],
    'B': [2, 3, 4, 5]
}

df = pd.DataFrame(data)

df.index = [1, 2, 3, 4]

In [3]:
df

A  B
1  1  2
2  1  3
3  3  4
4  3  5

In [5]:
nodes = pd.concat([df['A'], df['B']]).unique()
size = max(nodes) + 1

In [6]:
size

6

In [8]:
adjacency_matrix = np.zeros((size, size), dtype=int)


In [11]:
for index, row in df.iterrows():
    u = row['A']
    v = row['B']
    
    
    adjacency_matrix[u][v] = 1
    adjacency_matrix[v][u] = 1

print("Итоговая матрица смежности")
print(adjacency_matrix)


Итоговая матрица смежности
[[0 0 0 0 0 0]
 [0 0 1 1 0 0]
 [0 1 0 0 0 0]
 [0 1 0 0 1 1]
 [0 0 0 1 0 0]
 [0 0 0 1 0 0]]
